version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db_v4
    env_file: ".env"
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB" ]
      interval: 5s
      retries: 5
      timeout: 3s

  app:
    build: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    env_file: ".env"
    volumes:
      - .:/src
    ports:
      - "8002:8000"

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]

volumes:
  db_data:
  redis_data: